// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: simple.proto

package types

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// SubStore contains the name and root hash for a substore
type SubStore struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Root []byte `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
}

func (m *SubStore) Reset()                    { *m = SubStore{} }
func (m *SubStore) String() string            { return proto.CompactTextString(m) }
func (*SubStore) ProtoMessage()               {}
func (*SubStore) Descriptor() ([]byte, []int) { return fileDescriptorSimple, []int{0} }

func (m *SubStore) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SubStore) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

// SimpleStep is an inner node between SubStore and the
// MultiStore root
type SimpleStep struct {
	Left  []byte `protobuf:"bytes,1,opt,name=left,proto3" json:"left,omitempty"`
	Right []byte `protobuf:"bytes,2,opt,name=right,proto3" json:"right,omitempty"`
}

func (m *SimpleStep) Reset()                    { *m = SimpleStep{} }
func (m *SimpleStep) String() string            { return proto.CompactTextString(m) }
func (*SimpleStep) ProtoMessage()               {}
func (*SimpleStep) Descriptor() ([]byte, []int) { return fileDescriptorSimple, []int{1} }

func (m *SimpleStep) GetLeft() []byte {
	if m != nil {
		return m.Left
	}
	return nil
}

func (m *SimpleStep) GetRight() []byte {
	if m != nil {
		return m.Right
	}
	return nil
}

// MultiStoreProof is a merkle proof from a SubStore root
// up to the MultiStore root
type MultiStoreProof struct {
	Root  []byte        `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	Path  []*SimpleStep `protobuf:"bytes,2,rep,name=path" json:"path,omitempty"`
	Store *SubStore     `protobuf:"bytes,3,opt,name=store" json:"store,omitempty"`
}

func (m *MultiStoreProof) Reset()                    { *m = MultiStoreProof{} }
func (m *MultiStoreProof) String() string            { return proto.CompactTextString(m) }
func (*MultiStoreProof) ProtoMessage()               {}
func (*MultiStoreProof) Descriptor() ([]byte, []int) { return fileDescriptorSimple, []int{2} }

func (m *MultiStoreProof) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *MultiStoreProof) GetPath() []*SimpleStep {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *MultiStoreProof) GetStore() *SubStore {
	if m != nil {
		return m.Store
	}
	return nil
}

func init() {
	proto.RegisterType((*SubStore)(nil), "types.SubStore")
	proto.RegisterType((*SimpleStep)(nil), "types.SimpleStep")
	proto.RegisterType((*MultiStoreProof)(nil), "types.MultiStoreProof")
}

func init() { proto.RegisterFile("simple.proto", fileDescriptorSimple) }

var fileDescriptorSimple = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0x4f, 0x6b, 0x84, 0x30,
	0x10, 0xc5, 0x89, 0x7f, 0x4a, 0x3b, 0x0a, 0xd2, 0xd0, 0x43, 0x8e, 0x41, 0x10, 0x72, 0xf2, 0x60,
	0xa1, 0xdf, 0xa2, 0x50, 0x92, 0x4f, 0xa0, 0x10, 0xab, 0xa0, 0x9b, 0x90, 0x8c, 0x87, 0xfd, 0xf6,
	0x8b, 0xe3, 0xba, 0xde, 0x5e, 0x32, 0xf3, 0x7e, 0x6f, 0x1e, 0x94, 0x71, 0x5e, 0xfd, 0x62, 0x5b,
	0x1f, 0x1c, 0x3a, 0x9e, 0xe3, 0xdd, 0xdb, 0x58, 0x77, 0xf0, 0x6e, 0xb6, 0xc1, 0xa0, 0x0b, 0x96,
	0x73, 0xc8, 0x6e, 0xfd, 0x6a, 0x05, 0x93, 0x4c, 0x7d, 0x68, 0xd2, 0xfb, 0x5f, 0x70, 0x0e, 0x45,
	0x22, 0x99, 0x2a, 0x35, 0xe9, 0xfa, 0x07, 0xc0, 0x10, 0xca, 0xa0, 0xf5, 0xfb, 0xc6, 0x62, 0x47,
	0x24, 0x57, 0xa9, 0x49, 0xf3, 0x2f, 0xc8, 0xc3, 0xfc, 0x3f, 0x9d, 0xb6, 0xe3, 0x51, 0x47, 0xa8,
	0x7e, 0xb7, 0x05, 0x67, 0x4a, 0xfb, 0x0b, 0xce, 0x8d, 0x2f, 0x3c, 0xbb, 0xf0, 0xbc, 0x81, 0xcc,
	0xf7, 0x38, 0x89, 0x44, 0xa6, 0xaa, 0xe8, 0x3e, 0x5b, 0x3a, 0xb4, 0xbd, 0x12, 0x35, 0x8d, 0x79,
	0x03, 0x79, 0xdc, 0x41, 0x22, 0x95, 0x4c, 0x15, 0x5d, 0x75, 0xee, 0x3d, 0xdb, 0xe8, 0x63, 0x3a,
	0xbc, 0x51, 0xdd, 0xef, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0x18, 0xb5, 0x57, 0x0b, 0xfe, 0x00,
	0x00, 0x00,
}
